## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
matrix:
  include:
    - os: linux
      julia: 1.0
      env: TESTCMD="xvfb-run julia"
    - os: linux
      julia: 1.3
      env: TESTCMD="xvfb-run julia"
    - os: linux
      julia: 1.4
      env: TESTCMD="xvfb-run julia"
    - os: linux
      julia: nightly
      env: TESTCMD="xvfb-run julia"
    - os: osx
      julia: 1.0
      env: TESTCMD="julia"
    - os: osx
      julia: 1.2
      env: TESTCMD="julia"
    - os: osx
      julia: nightly
      env: TESTCMD="julia"
  allow_failures:
    - julia: nightly

notifications:
  email: false

branches:
  only:
    - master

script:
  - julia --color=yes -e "using Pkg; if VERSION >= v\"1.1.0-rc1\"; Pkg.build(verbose=true); else Pkg.build(); end"
  - $TESTCMD --check-bounds=yes --color=yes -e 'using Pkg; Pkg.test("MeshCat", coverage=true)'
  - julia --color=yes -e 'using MeshCat; MeshCat.develop_meshcat_assets(true)'
  - julia --color=yes -e 'import Pkg; Pkg.build("MeshCat")'
after_success:
  - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
