name = "MeshCat"
uuid = "283c5d60-a78f-5afe-a0af-af636b173e11"
authors = ["Robin Deits <robin.deits@gmail.com>"]
version = "0.10.0"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
BinDeps = "9e28174c-4ba2-5203-b857-d8d62c4213ee"
Cassette = "7057c7e9-c182-5462-911a-8362d720325c"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
FFMPEG = "c87230d0-a227-11e9-1b43-d7ebe4e7570a"
GeometryTypes = "4d00f742-c7ba-57c2-abde-4428a4b178cb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MsgPack = "99f44e22-a591-53d1-9472-aa23ef4bd671"
Mux = "a975b10e-0019-58db-a62f-e48ff68538c9"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
WebSockets = "104b5d7c-a370-577a-8038-80a2059c5097"

[compat]
BinDeps = "1"
Cassette = "0.2.5, 0.3"
Colors = "0.9, 0.10, 0.11, 0.12"
CoordinateTransformations = "0.5"
DocStringExtensions = "0.5, 0.6, 0.7, 0.8"
FFMPEG = "0.2, 0.3"
GeometryTypes = "0.6, 0.7, 0.8"
MsgPack = "1"
Mux = "0.7"
Parameters = "0.10, 0.11, 0.12"
Requires = "0.5, 1"
Rotations = "0.8, 0.9, 0.10, 0.11, 0.13"
StaticArrays = "0.10, 0.11, 0.12"
WebSockets = "1"
julia = "0.7, 1"

[extras]
Blink = "ad839575-38b3-5650-b840-f874b8c74a25"
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
MeshIO = "7269a6da-0436-5bbc-96c2-40638cbb6118"
Meshing = "e6723b4c-ebff-59f1-b4b7-d97aa5274f73"
NBInclude = "0db19996-df87-5ea3-a455-e3a50d440464"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "MeshIO", "FileIO", "Meshing", "NBInclude", "Blink", "ColorTypes", "Pkg", "Random"]
